### ISSUE TITLE
Music App Ideas 

### ISSUE THREAD

**Issue by ItsJamie9494** [tau-OS/.github#1]
### Problem

tauOS iirc ships with Rhythmbox music player, which has one of the worst UIs I've seen. GNOME Music looks better, but has no functionality.

### Proposal

I propose forking the elementary OS Odin music player, and updating it for GTK4 and LibAdwaita.

**Comment by nothingneko** [comment]
We ship GNOME music. Although Rhythmbox should be installed if an iPod or other MP3 player is connected

**Comment by ItsJamie9494** [comment]
gonna move this to meta repo
